<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UserSecretsId>8a395a5a-6154-45db-bb85-53ba7d161f93</UserSecretsId>
		<DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="AutoMapper" Version="13.0.1" />
		<PackageReference Include="FluentValidation" Version="12.1.1" />
		<PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.22.1" />
		<PackageReference Include="Swashbuckle.AspNetCore" Version="8.1.4" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\eCommerce.Core\UserService.Core.csproj" />
		<ProjectReference Include="..\eCommerce.Infrastructure\UserService.Infrastructure.csproj" />
	</ItemGroup>

</Project>
